<?php
/**
 * Created by PhpStorm.
 * User: aurelwcs
 * Date: 08/01/19
 * Time: 08:56
 */

namespace BlackJack;


use PHPUnit\Framework\TestCase;

/**
 * Class BlackJackTest
 * @package BlackJack
 */
class BlackJackTest extends TestCase
{

    /**
     * @var BlackJack
     */
    private $blackJack;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->blackJack = new BlackJack();
    }

    /**
     * @test
     * @dataProvider getPlayerWinDecks
     */
    public function playerWin($player, $bank)
    {
        $this->assertEquals('player', $this->blackJack->play($player, $bank));
    }

    /**
     * @return array
     */
    public function getPlayerWinDecks()
    {
        return [
            'Player wins with a pair of nine' => [
                [9, 9], [5, 6],
            ],
            'Player wins with bank over twenty-one' => [
                [5, 5], [9, 9, 5]
            ],
            'Player wins with a pair of K' => [
                ['K', 'Q'], [8, 'J']
            ],
            'Player wins with A and K' => [
                ['A', 'K'], [8, 8]
            ],
            'Player wins with A and pair of eight' => [
                ['A', 8, 8], [8, 8]
            ]
        ];
    }

    /**
     * @test
     * @dataProvider getBankWinDecks
     */
    public function bankWin($player, $bank)
    {
        $this->assertEquals('bank', $this->blackJack->play($player, $bank));
    }

    public function getBankWinDecks()
    {
        return [
            'Bank wins with a pair of 9' => [
                [5, 6], [9, 9]
            ],
            'Bank wins with player over twenty-one' => [
                [9, 9, 5],[5, 5]
            ],
        ];

    }

}